StylesPath = .vale/styles
MinAlertLevel = suggestion
IgnoredScopes = code, tt, img, url, a
SkippedScopes = script, style, pre, figure, code, text.frontmatter
Vocab = Unikraft
Packages = Microsoft, write-good

# This is required since Vale doesn't officially support MDX
[formats]
mdx = md

[*.mdx]
BasedOnStyles = Microsoft, write-good, Unikraft

# Token and block ignores for MDX-specific syntax
TokenIgnores = (?sm)((?:import|export) .+?$), \
(?<!`)(<\w+ ?.+ ?\/>)(?!`), \
(<[A-Z]\w+>.+?<\/[A-Z]\w+>), \
(<[^>]*>), \
\{[^}]*\}, \
(`[^`]*`), \
(```[\s\S]*?```)

BlockIgnores = (?sm)```[\s\S]*?```$, (?s)\{/\*\s*vale off\s*\*/\}.*?\{/\*\s*vale on\s*\*/\}

CommentDelimiters = {/*, */}

# Ignore or enforce specific rules
write-good.E-Prime = NO
Microsoft.Passive = NO # We already have write-good.Passive
Microsoft.Headings = error
Microsoft.Wordiness = error
Microsoft.Vocab = NO
Microsoft.We = error
write-good.TooWordy = error
write-good.Passive = error
Microsoft.HeadingAcronyms = NO
Microsoft.HeadingPunctuation = NO
