#!/usr/bin/env python3
"""
Convert an examples README.md into an MDX guide with small post-processing.

Behavior:
- Read INPUT_FILE and determine TITLE from the first H1 (or use example name)
- Insert the Tabs import immediately after the H1 (or create an H1 from TITLE)
- Convert blockquote-style admonitions like:
  > **Note:**\n+  > line1\n+  > line2
  into:
  :::note\n  line1\n  line2\n  :::
- Rewrite absolute docs URLs back to site-relative paths
- Group adjacent titled code blocks into <CodeTabs> wrappers with syncKey
- Append a Source block when EXAMPLE_NAME is provided

Usage: transform_readme.py INPUT_FILE OUTPUT_FILE [EXAMPLE_NAME]
"""
from __future__ import annotations
import argparse
import os
import re
from pathlib import Path


# ANSI color codes
ANSI_RESET = '\x1b[0m'
ANSI_BOLD = '\x1b[1m'
ANSI_BOLD_OFF = '\x1b[22m'
ANSI_ITALIC = '\x1b[3m'
ANSI_ITALIC_OFF = '\x1b[23m'
ANSI_DARK_GRAY = '\x1b[90m'
ANSI_DARK_GRAY_256 = '\x1b[38;5;245m'
ANSI_GREEN = '\x1b[92m'
ANSI_LIGHT_BLUE = '\x1b[94m'
ANSI_KRAFT_HEADER = '\x1b[0;1;39m'
ANSI_KRAFT_RUNNING = '\x1b[0;32m'
ANSI_KRAFT_STANDBY = '\x1b[0;36m'
ANSI_KRAFT_STOPPED = '\x1b[0;31m'
ANSI_KRAFT_STARTING = '\x1b[92m'
ANSI_UNIKRAFT_RUNNING = '\x1b[38;2;0;188;125m'
ANSI_UNIKRAFT_STANDBY = '\x1b[38;2;43;127;255m'
ANSI_UNIKRAFT_STOPPED = '\x1b[38;2;236;0;63m'
ANSI_UNIKRAFT_STARTING = '\x1b[38;2;144;161;185m'

STATE_COLORS_DEFAULT: dict[str, str] = {
    "running": ANSI_GREEN,
    "standby": ANSI_LIGHT_BLUE,
    "stopped": '\x1b[91m',
    "starting": ANSI_GREEN,
    "template": ANSI_LIGHT_BLUE,
}

STATE_COLORS_BY_SOURCE: dict[str, dict[str, str]] = {
    "unikraft": {
        "running": ANSI_UNIKRAFT_RUNNING,
        "standby": ANSI_UNIKRAFT_STANDBY,
        "stopped": ANSI_UNIKRAFT_STOPPED,
        "starting": ANSI_UNIKRAFT_STARTING,
        "template": ANSI_UNIKRAFT_STANDBY,
    },
    "kraft": {
        "running": ANSI_KRAFT_RUNNING,
        "standby": ANSI_KRAFT_STANDBY,
        "stopped": ANSI_KRAFT_STOPPED,
        "starting": ANSI_KRAFT_STARTING,
        "template": ANSI_KRAFT_STANDBY,
    },
}

# Import statement for Tabs component
TABS_IMPORT = 'import { Tabs, TabsContent, TabsList, TabsTrigger } from "zudoku/ui/Tabs"\n\n'
GENERATED_FILE_COMMENT = "{/* THIS FILE WAS AUTOGENERATED FROM THE PUBLIC EXAMPLE REPOSITORY. DO NOT EDIT THIS FILE DIRECTLY. */}\n\n"

# Regex patterns
FENCE_PATTERN = re.compile(r"(^```([^\n]*)\n)(.*?)(\n```)$", flags=re.M | re.S)
FRONT_MATTER_PATTERN = re.compile(r"^---\n.*?\n---\n\s*", flags=re.S)
ADMONITION_PATTERN = re.compile(r"^(\s*)>\s*\*\*([^*]+?):?\*\*:?\s*$")
TITLE_VALUE_PATTERN = re.compile(r'title\s*=\s*"([^"]*)"', flags=re.I)

CODETABS_SPACER = '\n\n<div style={{ marginTop: \'0.8em\' }} />\n\n'

def has_fence_title(fence_info: str) -> bool:
    m = TITLE_VALUE_PATTERN.search(fence_info or "")
    return bool(m and m.group(1).strip())


def detect_cli_source(fence_info: str) -> str:
    """Infer CLI source from fence metadata, defaulting to generic colors."""
    info = (fence_info or "").lower()
    if 'title="unikraft"' in info:
        return "unikraft"
    if 'title="kraft"' in info:
        return "kraft"
    return "default"


def get_state_color_map(fence_info: str) -> dict[str, str]:
    """Get per-source state colors from the block metadata."""
    source = detect_cli_source(fence_info)
    return STATE_COLORS_BY_SOURCE.get(source, STATE_COLORS_DEFAULT)


def extract_title(text: str, example_name: str | None) -> str:
    m = re.search(r"^# (.+)$", text, flags=re.M)
    if m:
        return m.group(1).strip()
    if example_name:
        return example_name
    return ""


def ensure_front_matter(text: str, title: str) -> str:
    """Ensure YAML front-matter with title at the top, replacing existing if present."""
    fm = f"---\ntitle: \"{title}\"\n---\n\n{GENERATED_FILE_COMMENT}"
    m = FRONT_MATTER_PATTERN.match(text)
    if m:
        return fm + text[m.end():]
    return fm + text


def insert_tabs_import(text: str, title: str) -> str:
    """Insert Tabs import after front-matter or H1, avoiding duplicates."""
    # If import already exists, do nothing
    if "zudoku/ui/Tabs" in text:
        return text
    # If there's YAML front-matter at the top, insert after it.
    m_fm = FRONT_MATTER_PATTERN.match(text)
    if m_fm:
        insert_at = m_fm.end()
        return text[:insert_at] + TABS_IMPORT + text[insert_at:]

    # Find first H1 and insert after it
    m = re.search(r"(^# .+)$", text, flags=re.M)
    if m:
        insert_at = m.end(1)
        return text[:insert_at] + "\n" + TABS_IMPORT + text[insert_at:]

    # No front-matter nor H1: create H1 from title if available
    if title:
        return f"# {title}\n\n{TABS_IMPORT}\n" + text

    # Fallback: prepend import
    return TABS_IMPORT + "\n" + text


def convert_admonitions(text: str) -> str:
    """Convert blockquote-style admonitions to ::: syntax."""
    lines = text.splitlines()
    out = []
    i = 0

    while i < len(lines):
        m = ADMONITION_PATTERN.match(lines[i])
        if m:
            indent = m.group(1)
            label = m.group(2).strip().rstrip(":")
            key = label.lower().replace(" ", "-")
            i += 1
            block = []
            quote_line_pattern = re.compile(rf"^{re.escape(indent)}> ?(.*)$")
            while i < len(lines):
                q = quote_line_pattern.match(lines[i])
                if not q:
                    break
                block.append(indent + q.group(1))
                i += 1
            # Start admonition block
            out.append(f"{indent}:::{key}")
            out.extend(block)
            out.append(f"{indent}:::")
        else:
            out.append(lines[i])
            i += 1
    return "\n".join(out) + ("\n" if text.endswith("\n") else "")


def rewrite_urls(text: str) -> str:
    """Rewrite absolute docs URLs to site-relative paths."""
    # General rule for any other /docs/ link
    text = re.sub(r"https://unikraft.com/docs/([^\s\)]+)", r"/\1", text)
    return text


def remove_cli_section_labels(text: str) -> str:
    """Remove bold CLI section labels from examples READMEs."""
    pattern = re.compile(
        r"(?m)^\*\*(Using the unikraft CLI \(Recommended\)|Using the legacy kraft CLI)\*\*\s*$\n?"
    )
    return pattern.sub("", text)


def convert_code_tabs(text: str) -> str:
    """Group adjacent code blocks containing title="..." inside a <CodeTabs> wrapper."""
    block_pattern = re.compile(r"(```([^\n]*?title=\"([^\"]+)\"[^\n]*)\n.*?\n```)", flags=re.S)

    matches = list(block_pattern.finditer(text))
    if not matches:
        return text

    groups: list[list] = []
    # Separator that caused the split *before* groups[i]; None for the first group.
    group_separators: list[str | None] = []
    current_group = [matches[0]]
    current_sep: str | None = None

    for i in range(1, len(matches)):
        prev = current_group[-1]
        curr = matches[i]

        # Check if only whitespace or the word "or" exists between blocks
        between = text[prev.end():curr.start()].strip().lower()

        prev_info = prev.group(2).strip().lower()
        curr_info = curr.group(2).strip().lower()

        # "or" between an ansi (output) block and a bash (command) block marks
        # the boundary between two CLI alternatives (e.g. listing cmd+output for
        # unikraft followed by cmd+output for kraft). Break the group here so
        # the two groups can later be interleaved into per-position <CodeTabs>.
        if between == "or" and prev_info.startswith("ansi") and curr_info.startswith("bash"):
            groups.append(current_group)
            group_separators.append(current_sep)
            current_sep = between
            current_group = [curr]
        elif between in ["", "or"]:
            current_group.append(curr)
        else:
            groups.append(current_group)
            group_separators.append(current_sep)
            current_sep = between
            current_group = [curr]
    groups.append(current_group)
    group_separators.append(current_sep)

    # Build a list of (start, end, replacement) spans to apply to the text.
    # When two consecutive equal-length groups were split by "or" (cmd+output
    # pattern), zip them positionally so that:
    #   [bash:A, ansi:A] "or" [bash:B, ansi:B]
    # becomes:
    #   <CodeTabs>(bash:A, bash:B)</CodeTabs>
    #   <CodeTabs>(ansi:A, ansi:B)</CodeTabs>
    replacements: list[tuple[int, int, str]] = []
    i = 0
    while i < len(groups):
        if (
            i + 1 < len(groups)
            and group_separators[i + 1] == "or"
            and len(groups[i]) == len(groups[i + 1])
            and len(groups[i]) > 1
        ):
            grp_a = groups[i]
            grp_b = groups[i + 1]
            parts = []
            for j in range(len(grp_a)):
                blocks = sorted(
                    [grp_a[j].group(1), grp_b[j].group(1)],
                    key=lambda b: (0 if 'title="unikraft"' in b else 1),
                )
                parts.append(
                    '<CodeTabs syncKey="cli">\n\n' + "\n\n".join(blocks) + "\n\n</CodeTabs>"
                )
            replacement = CODETABS_SPACER.join(parts)
            # Replace the entire span covering both groups (including the "or" between them)
            start = grp_a[0].start()
            end = grp_b[-1].end()
            replacements.append((start, end, replacement))
            i += 2
        else:
            group = groups[i]
            if len(group) > 1:
                blocks = sorted(
                    [m.group(1) for m in group],
                    key=lambda b: (0 if 'title="unikraft"' in b else 1),
                )
                tabs_str = '<CodeTabs syncKey="cli">\n\n' + "\n\n".join(blocks) + "\n\n</CodeTabs>"
                replacements.append((group[0].start(), group[-1].end(), tabs_str))
            i += 1

    out = text
    for start, end, replacement in reversed(replacements):
        out = out[:start] + replacement + out[end:]

    return out


def color_bracket_and_bullet(line: str, gray: str = ANSI_DARK_GRAY_256) -> str:
    """Color the [●] Deployed successfully! line."""
    line = line.replace('[', f'{gray}[{ANSI_RESET}')
    line = line.replace('●', f'{ANSI_GREEN}●{ANSI_RESET}')
    line = line.replace(']', f'{gray}]{ANSI_RESET}')
    return line


def color_box_drawing_line(
    line: str,
    state_colors: dict[str, str],
    gray: str = ANSI_DARK_GRAY_256,
) -> str:
    """Color lines with box-drawing characters and labels."""
    # Match pattern like " ├────── name: value" or " │" (empty line)
    colon_match = re.search(r'^(\s*)((?:│|├|└))((?:─*)\s*)([^:]+)(:)(.*)$', line)

    if colon_match:
        leading_space = colon_match.group(1)  # leading whitespace
        box_char = colon_match.group(2)       # │, ├, or └
        dashes = colon_match.group(3)         # ─── and spaces
        label = colon_match.group(4)          # the label (e.g., "name")
        colon = colon_match.group(5)          # the colon
        value = colon_match.group(6)          # the value after colon

        # Color the box character
        box_colored = f'{gray}{box_char}{ANSI_RESET}'

        # Color all dashes
        dashes_colored = dashes.replace('─', f'{gray}─{ANSI_RESET}')

        # Color the label in dark gray (but not the colon)
        label_colored = f'{gray}{label}{ANSI_RESET}{colon}'

        # Check if this is the state line and color the value
        if 'state' in label.lower():
            # Color the state value (first word after colon and spaces)
            value_match = re.search(r'^(\s*)(\S+)(.*)$', value)
            if value_match:
                value_spaces = value_match.group(1)
                state_value = value_match.group(2)
                rest = value_match.group(3)
                color = state_colors.get(state_value.lower(), ANSI_GREEN)
                value = f'{value_spaces}{color}{state_value}{ANSI_RESET}{rest}'

        return leading_space + box_colored + dashes_colored + label_colored + value
    else:
        # No colon, just color the box-drawing characters
        for char in ['│', '├', '└', '─']:
            line = line.replace(char, f'{gray}{char}{ANSI_RESET}')
        return line


def color_deployed_block(text: str) -> str:
    """Find and colorize deployed successfully blocks with ANSI codes."""
    def repl(m):
        fence_start = m.group(1)
        lang = (m.group(2) or "").strip()
        body = m.group(3)
        fence_end = m.group(4)
        if not has_fence_title(lang):
            return m.group(0)
        state_colors = get_state_color_map(lang)

        # Only operate on blocks that contain the deployed-success marker text.
        if 'deployed successfully!' not in body.lower():
            return m.group(0)

        # Check if this block already has proper ANSI coloring applied
        if f'{ANSI_DARK_GRAY}│{ANSI_RESET}' in body or f'{ANSI_DARK_GRAY}├{ANSI_RESET}' in body:
            return m.group(0)

        # Ensure the fence is marked as 'ansi' for proper rendering,
        # preserving other attributes like title="..."
        if 'ansi' not in lang.lower():
            rest_attrs = re.sub(r'^\S*', '', lang).strip()
            fence_start = (f'```ansi {rest_attrs}\n' if rest_attrs else '```ansi\n')

        # Process line by line to add colors
        lines = body.split('\n')
        colored_lines = []

        for line in lines:
            # Skip empty lines
            if not line.strip():
                colored_lines.append(line)
                continue

            # Color the bracket and bullet line: [●] Deployed successfully!
            if '●' in line and 'deployed successfully' in line.lower():
                colored_lines.append(color_bracket_and_bullet(line, gray=ANSI_DARK_GRAY_256))
                continue

            # Color lines with box-drawing characters (│, ├, └, ─)
            if any(char in line for char in ['│', '├', '└', '─']):
                colored_lines.append(
                    color_box_drawing_line(
                        line,
                        state_colors=state_colors,
                        gray=ANSI_DARK_GRAY_256,
                    )
                )
            else:
                colored_lines.append(line)

        body = '\n'.join(colored_lines)
        return fence_start + body + fence_end

    return FENCE_PATTERN.sub(repl, text)


def find_state_column_index(header_line: str) -> int | None:
    """Find the index of the STATE column in a table header."""
    header_tokens = re.split(r"\s{2,}", header_line.strip())
    for i, token in enumerate(header_tokens):
        if token.strip().upper() == "STATE":
            return i
    return None


def is_volume_listing_header(header_line: str) -> bool:
    cols = [c.strip().upper() for c in re.split(r'\s{2,}', header_line.strip()) if c.strip()]
    if "STATE" not in cols or "SIZE" not in cols or "NAME" not in cols:
        return False
    return any(c == "CREATED" or c == "CREATED AT" for c in cols)


def looks_like_listing_header(line: str) -> bool:
    """Detect uppercase table headers like NAME/FQDN/SERVICES/CREATED AT."""
    if '\x1b[' in line:
        return False

    cols = [c.strip() for c in re.split(r'\s{2,}', line.strip()) if c.strip()]
    if len(cols) < 2:
        return False

    upper_like = 0
    for col in cols:
        if re.fullmatch(r'[A-Z0-9][A-Z0-9\- ]*', col):
            upper_like += 1

    return upper_like >= 2


def find_listing_header_index(lines: list[str]) -> int | None:
    for idx, line in enumerate(lines):
        if looks_like_listing_header(line):
            return idx
    return None


def format_header_token(token: str, source: str) -> str:
    """Apply source-specific header styling."""
    if source == "kraft":
        return f"{ANSI_KRAFT_HEADER}{token}{ANSI_RESET}"
    if source == "unikraft":
        return f"{ANSI_BOLD}{token}{ANSI_BOLD_OFF}"
    return f"{ANSI_BOLD}{token}{ANSI_RESET}"


def bold_table_header(header_line: str, source: str) -> str:
    """Make each token in the table header bold."""
    if '\x1b[' in header_line:
        return header_line

    pieces = re.split(r'(\s{2,})', header_line)
    cols = pieces[0::2]
    seps = pieces[1::2]

    for i, col in enumerate(cols):
        token = col.strip()
        if token and ANSI_BOLD not in token:
            cols[i] = col.replace(token, format_header_token(token, source), 1)

    result = ""
    for i, col in enumerate(cols):
        result += col
        if i < len(seps):
            result += seps[i]
    return result


def is_unikraft_run_output(body: str) -> bool:
    """Detect `unikraft run`-style YAML-ish output blocks."""
    return bool(
        re.search(r'^(?:\x1b\[[0-9;]*m)*metro(?:\x1b\[[0-9;]*m)*:\s+\S', body, flags=re.M)
        and re.search(r'^(?:\x1b\[[0-9;]*m)*resources(?:\x1b\[[0-9;]*m)*:\s*$', body, flags=re.M)
    )


def is_unikraft_structured_output(body: str) -> bool:
    """Detect YAML-like unikraft key/value output blocks beyond `run` output."""
    if any(ch in body for ch in ("│", "├", "└")):
        return False

    lines = [line for line in body.splitlines() if line.strip()]
    if not lines:
        return False

    kv_count = 0
    for line in lines:
        plain = re.sub(r'\x1b\[[0-9;]*m', '', line)
        if re.match(r'^\s*-?\s*[a-z][a-z0-9-]*\s*:\s*.*$', plain):
            kv_count += 1

    return kv_count >= 3


def style_unikraft_run_fields(body: str) -> str:
    """Style unikraft run keys: top-level bold, nested keys italic."""
    lines = body.splitlines()
    out: list[str] = []

    for line in lines:
        top = re.match(r'^([a-z][a-z0-9-]*)(:)(\s*.*)$', line)
        if top:
            key, colon, rest = top.groups()
            if line.startswith(ANSI_BOLD):
                out.append(line)
                continue
            out.append(f"{ANSI_BOLD}{key}{ANSI_BOLD_OFF}{colon}{rest}")
            continue

        list_key = re.match(r'^(-\s*[a-z][a-z0-9-]*)(:)(\s*.*)$', line)
        if list_key:
            key, colon, rest = list_key.groups()
            if line.startswith(ANSI_ITALIC):
                out.append(line)
                continue
            out.append(f"{ANSI_ITALIC}{key}{ANSI_ITALIC_OFF}{colon}{rest}")
            continue

        nested = re.match(r'^(\s+)(-?\s*[a-z][a-z0-9-]*)(:)(\s*.*)$', line)
        if nested:
            indent, key, colon, rest = nested.groups()
            if line.startswith(ANSI_ITALIC):
                out.append(line)
                continue
            out.append(f"{ANSI_ITALIC}{indent}{key}{ANSI_ITALIC_OFF}{colon}{rest}")
            continue

        out.append(line)

    return "\n".join(out)


def color_state_value_in_row(
    line: str,
    state_col: int,
    state_colors: dict[str, str],
    source: str,
    volume_listing: bool,
    force_non_error_color: str | None = None,
) -> str:
    """Color the state value in a table row."""
    pieces = re.split(r'(\s{2,})', line)
    cols = pieces[0::2]
    seps = pieces[1::2]

    for i, col in enumerate(cols):
        # Keep listing values plain; only header should remain bold.
        col = re.sub(r'\x1b\[1m([^\x1b]+?)\x1b\[22m', r'\1', col)
        col = re.sub(r'\x1b\[0;1;39m([^\x1b]+?)\x1b\[0m', r'\1', col)
        cols[i] = col

    if len(cols) > state_col:
        raw_val = cols[state_col]
        val = raw_val.strip()
        if val and ANSI_RESET not in val:
            clean_val = re.sub(r'\x1b\[[0-9;]*m', '', val).lower()
            if volume_listing and source != "unikraft":
                color = None
            elif force_non_error_color is not None:
                error_words = {"error", "failed", "faulted", "corrupted", "unavailable"}
                if clean_val == "template":
                    color = state_colors.get("template", ANSI_LIGHT_BLUE)
                elif clean_val in error_words:
                    color = state_colors.get("stopped", '\x1b[91m')
                else:
                    color = force_non_error_color
            else:
                color = state_colors.get(clean_val, ANSI_GREEN)
            if color is not None:
                colored = f"{color}{val}{ANSI_RESET}"
                cols[state_col] = raw_val.replace(val, colored, 1)

    # Reconstruct using original separators to preserve spacing
    result = ""
    for i, col in enumerate(cols):
        result += col
        if i < len(seps):
            result += seps[i]
    return result


def clean_listing_row_emphasis(line: str) -> str:
    pieces = re.split(r'(\s{2,})', line)
    cols = pieces[0::2]
    seps = pieces[1::2]

    for i, col in enumerate(cols):
        col = re.sub(r'\x1b\[1m([^\x1b]+?)\x1b\[22m', r'\1', col)
        col = re.sub(r'\x1b\[0;1;39m([^\x1b]+?)\x1b\[0m', r'\1', col)
        cols[i] = col

    out = ""
    for i, col in enumerate(cols):
        out += col
        if i < len(seps):
            out += seps[i]
    return out


def color_standalone_template_token(text: str, color: str | None) -> str:
    if not color:
        return text
    return re.sub(r'(?<![A-Za-z])template(?![A-Za-z])', lambda m: f"{color}{m.group(0)}{ANSI_RESET}", text, flags=re.I)


def color_state_in_table_blocks(text: str) -> str:
    """Color state values in table-style fenced blocks (STATE column) based on STATE_COLORS."""
    def repl(m):
        lang = (m.group(2) or "").strip()
        if not has_fence_title(lang):
            return m.group(0)
        source = detect_cli_source(lang)
        state_colors = get_state_color_map(lang)
        fence_start = m.group(1)
        body = m.group(3)
        fence_end = m.group(4)

        if source == "unikraft" and (is_unikraft_run_output(body) or is_unikraft_structured_output(body)):
            body = style_unikraft_run_fields(body)

        lines = body.splitlines()

        # Find listing-like header line.
        header_idx = find_listing_header_index(lines)

        if header_idx is None:
            if body != m.group(3):
                return fence_start + body + fence_end
            return m.group(0)

        # Always bold listing header, even if there is no STATE column.
        new_lines = lines[:header_idx]
        new_lines.append(bold_table_header(lines[header_idx], source).rstrip('\n'))

        # Find the STATE column index
        state_col = find_state_column_index(lines[header_idx])
        volume_listing = is_volume_listing_header(lines[header_idx])
        if state_col is None:
            for row in lines[header_idx + 1:]:
                if row.strip() == "":
                    new_lines.append(row)
                else:
                    new_lines.append(clean_listing_row_emphasis(row))
            return fence_start + "\n".join(new_lines) + fence_end

        # Process data rows
        j = header_idx + 1
        force_non_error_color = state_colors.get("running", ANSI_GREEN) if volume_listing else None
        while j < len(lines) and lines[j].strip() != "":
            row = color_state_value_in_row(
                lines[j],
                state_col,
                state_colors,
                source,
                volume_listing,
                force_non_error_color=force_non_error_color,
            ).rstrip('\n')
            new_lines.append(row)
            j += 1

        # Append any remaining lines
        new_lines.extend(lines[j:])
        new_body = "\n".join(new_lines)
        return fence_start + new_body + fence_end

    return FENCE_PATTERN.sub(repl, text)


def color_yaml_deploy_block(text: str) -> str:
    """Color state values in YAML-style unikraft deploy output blocks."""
    def repl(m):
        lang = (m.group(2) or "").strip()
        if not has_fence_title(lang):
            return m.group(0)
        state_colors = get_state_color_map(lang)
        body = m.group(3)

        # Only target blocks that look like unikraft YAML deploy output:
        # must have 'state:' and 'name:' but NOT the kraft box-drawing style.
        if 'deployed successfully!' in body.lower():
            return m.group(0)
        if not re.search(r'^state:\s+\S', body, re.M):
            return m.group(0)
        if not re.search(r'^name:\s+\S', body, re.M):
            return m.group(0)
        # Skip if already colorized
        if ANSI_RESET in body and re.search(r'\x1b\[[0-9;]*m(starting|running|standby|stopped|template)', body, re.I):
            return m.group(0)

        lines = body.split('\n')
        colored_lines = []
        for line in lines:
            state_m = re.match(r'^(state:)(\s+)(\S+)(.*)$', line, re.I)
            if state_m:
                key = state_m.group(1)
                spaces = state_m.group(2)
                val = state_m.group(3)
                rest = state_m.group(4)
                color = state_colors.get(val.lower(), ANSI_GREEN)
                colored_lines.append(f'{key}{spaces}{color}{val}{ANSI_RESET}{rest}')
            else:
                colored_lines.append(line)
        new_body = '\n'.join(colored_lines)
        return m.group(1) + new_body + m.group(4)

    return FENCE_PATTERN.sub(repl, text)


def wrap_vale_off(text: str) -> str:
    """Wrap the content body in {/* vale off */} / {/* vale on */} comments."""
    # Determine where the preamble (front matter + tabs import) ends
    insert_at = 0
    m_fm = FRONT_MATTER_PATTERN.match(text)
    if m_fm:
        insert_at = m_fm.end()
    # Skip past the Tabs import line if present
    if text[insert_at:].startswith("import {"):
        end_of_import = text.find("\n\n", insert_at)
        if end_of_import != -1:
            insert_at = end_of_import + 2

    before = text[:insert_at]
    body = text[insert_at:].rstrip("\n")
    return before + "{/* vale off */}\n" + body + "\n{/* vale on */}\n"


def main(argv: list[str] | None = None) -> int:
    """Main entry point for the README to MDX transformation script."""
    p = argparse.ArgumentParser(
        description="Convert examples README.md into an MDX guide with ANSI coloring"
    )
    p.add_argument("input_file", help="Path to input README.md file")
    p.add_argument("output_file", help="Path to output MDX file")
    p.add_argument("example_name", nargs="?", default="", help="Optional example name for title")
    args = p.parse_args(argv)

    inp = Path(args.input_file)
    out = Path(args.output_file)
    example_name = args.example_name or None

    txt = inp.read_text(encoding="utf-8")

    # Determine title
    title = os.environ.get('TITLE') or extract_title(txt, example_name)

    # Apply transformations in sequence
    content = ensure_front_matter(txt, title)
    content = re.sub(r"(?m)^# .+\n", "", content, count=1)  # Remove first H1
    content = insert_tabs_import(content, title)
    content = convert_admonitions(content)
    content = rewrite_urls(content)
    content = remove_cli_section_labels(content)
    content = convert_code_tabs(content)
    content = color_deployed_block(content)
    content = color_yaml_deploy_block(content)
    content = color_state_in_table_blocks(content)
    content = wrap_vale_off(content)

    out.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
