name: cleanup-www

description: |
  Destroys the Unikraft landing and docs website (www).

inputs:
  name:
    required: true
    description: Name of the service.
  metro:
    required: false
    description: Unikraft Cloud Metro.
    default: was1
  delete-image:
    required: false
    description: Also delete the image.
    default: "false"

runs:
  using: composite
  steps:
  - name: Delete Service
    if: always()
    id: service
    shell: bash
    run: |
      # Delete all instances in the service before removing the service
      unikraft instances delete \
        --filter "service.name==${{ inputs.name }},metro==${{ inputs.metro }}" \
        --force;

      unikraft services delete \
        --filter "name==${{ inputs.name }},metro==${{ inputs.metro }}" \
        --force;

  - name: Delete Image
    if: ${{ inputs.delete-image }}
    id: image
    shell: bash
    run: |
      unikraft images delete "internal/${{ inputs.name }}:latest";
