name: check/pr

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [prod-staging]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Run check-pr
      uses: unikraft-cloud/x/.github/actions/check-pr@prod-staging

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: errata-ai/vale-action@v2.1.1
      with:
        reporter: github-pr-review
        token: ${{secrets.GH_PAT}}
        files: pages
        fail_on_error: true
